
name: Deploy to S3 and Lambda

on:
  push:
    branches: ["develop", "release/*"]

env:
  AWS_REGION: ap-northeast-2
  BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
  FUNCTION_NAME: chu-some-chu-some
  
jobs:
  deploy:
    name: Deploy to lambda
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
    - name: Compress python code to zip
      run: |
        cd lambda_ai
        zip -r lambda.zip ./*
        aws lambda update-function-code --function-name ${{env.FUNCTION_NAME}} --zip-file fileb://lambda.zip
